---@module 'debugging.command_descs'
--- One-line descriptions of the `:Debug` routes, keyed `"<category> <action>"` (or just
--- `"<category>"` for the free-form ones), for the composer option float and the generated docs.
--- Wording follows docs/commands.md.

---@type table<string, string>
return {
  ["autocmds all"] = "Sources-vs-runtime view of autocmds, with the diff",
  ["autocmds runtime"] = "Live autocmds for an event / pattern",
  ["autocmds sources"] = "Static source-code audit of autocmd call sites",
  ["cursor state"] = "Cursor, window and buffer state",
  ["dump"] = "Dump a global Lua variable (or the word under the cursor)",
  ["health"] = "Run :checkhealth debugging",
  ["indent show"] = "Print the indent options",
  ["indent treesitter"] = "Prefer Tree-sitter indent (true) or set cindent/smartindent on (false)",
  ["inspect buffer"] = "Buffer-scoped options and state",
  ["inspect tab"] = "Tab page: windows and buffers",
  ["inspect window"] = "Window-scoped options and state",
  ["keylogger start"] = "Log keys typed in the current terminal buffer (optionally to a file)",
  ["keylogger stop"] = "Stop the key logger",
  ["markdown inline"] = "Gather markdown inline-highlight debug info",
  ["markdown log"] = "Open the markdown debug log",
  ["messages capture"] = "Capture :messages to a file and the clipboard",
  ["messages clear"] = "Close the recent-messages popups",
  ["messages show"] = "Popup with the recent non-error messages (last 10 s, extendable)",
  ["module reload"] = "Reload the Lua module of the current buffer",
  ["neotest adapters"] = "Configured (neotest.setup) vs registered adapters",
  ["neotest discover"] = "Positions per registered adapter, tests in total",
  ["neotest file"] = "Does any adapter's is_test_file() want this file?",
  ["neotest framework"] = "Test-framework marker files and package.json frameworks found in the cwd",
  ["neotest root"] = "The project root each adapter derives, and its markers",
  ["neotest state"] = "The current buffer's neotest tree",
  ["neotree backup-clean"] = "Delete neo-tree safety backups older than 7 days",
  ["neotree backup-list"] = "List the neo-tree safety backups",
  ["neotree dryrun-report"] = "Report what a dry run would have done",
  ["neotree dryrun-toggle"] = "Toggle the neo-tree dry-run mode",
  ["neotree exit"] = "Leave neo-tree quarantine",
  ["neotree queue-clear"] = "Clear the neo-tree operation queue",
  ["neotree queue-status"] = "Show the neo-tree operation queue",
  ["neotree restart"] = "Restart the neo-tree watchers",
  ["neotree status"] = "Neo-tree quarantine status",
  ["noice all"] = "Popup with the recent messages of every level",
  ["noice errors"] = "Popup with the recent error messages",
  ["performance startup"] = "Benchmark startup time and list the slowest sourced scripts",
  ["proc log"] = "Open the process-call log",
  ["proc start"] = "Log the duration of system()/jobstart calls; slow ones get a traceback",
  ["proc status"] = "Show whether the process logger runs",
  ["proc stop"] = "Stop logging and restore the wrapped functions",
  ["proc watch"] = "External process-tree watcher for UI freezes (Windows only)",
  ["report buf"] = "Buffer report to :messages",
  ["report tab"] = "Tab report to :messages",
  ["report win"] = "Window report to :messages (optionally for a window id)",
}
